package com.project.hotel.model;

// default package
// Generated Nov 5, 2016 8:08:26 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbookingUser generated by hbm2java
 */
@Entity
@Table(name = "TBOOKING_USER", catalog = "hotelmgmt")
public class TbookingUser implements java.io.Serializable {

	private int bookingUserId;
	private String bookingRefNo;
	private Date bookingDt;
	private double totalPrice;

	public TbookingUser() {
	}

	public TbookingUser(int bookingUserId, String bookingRefNo, Date bookingDt,
			double totalPrice) {
		this.bookingUserId = bookingUserId;
		this.bookingRefNo = bookingRefNo;
		this.bookingDt = bookingDt;
		this.totalPrice = totalPrice;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "BOOKING_USER_ID", unique = true, nullable = false)
	public int getBookingUserId() {
		return this.bookingUserId;
	}

	public void setBookingUserId(int bookingUserId) {
		this.bookingUserId = bookingUserId;
	}

	@Column(name = "BOOKING_REF_NO", nullable = false, length = 20)
	public String getBookingRefNo() {
		return this.bookingRefNo;
	}

	public void setBookingRefNo(String bookingRefNo) {
		this.bookingRefNo = bookingRefNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BOOKING_DT", nullable = false, length = 19)
	public Date getBookingDt() {
		return this.bookingDt;
	}

	public void setBookingDt(Date bookingDt) {
		this.bookingDt = bookingDt;
	}

	@Column(name = "TOTAL_PRICE", nullable = false, precision = 22, scale = 0)
	public double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}

}
