package com.project.hotel.model;

// default package
// Generated Nov 5, 2016 8:08:26 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbookedRoomDetails generated by hbm2java
 */
@Entity
@Table(name = "TBOOKED_ROOM_DETAILS", catalog = "hotelmgmt")
public class TbookedRoomDetails implements java.io.Serializable {

	private int bookedRmDtlId;
	private Date checkinDt;
	private Date checkoutDt;
	private int noOfRoomsBooked;
	private Thotel hotel;
	private TbookingUser bookingUser;

	public TbookedRoomDetails() {
	}

	public TbookedRoomDetails(int bookedRmDtlId, Date checkinDt, Date checkoutDt) {
		this.bookedRmDtlId = bookedRmDtlId;
		this.checkinDt = checkinDt;
		this.checkoutDt = checkoutDt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "BOOKED_RM_DTL_ID", nullable = false)
	public int getBookedRmDtlId() {
		return this.bookedRmDtlId;
	}

	public void setBookedRmDtlId(int bookedRmDtlId) {
		this.bookedRmDtlId = bookedRmDtlId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHECKIN_DT", nullable = false, length = 10)
	public Date getCheckinDt() {
		return this.checkinDt;
	}

	public void setCheckinDt(Date checkinDt) {
		this.checkinDt = checkinDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHECKOUT_DT", nullable = false, length = 10)
	public Date getCheckoutDt() {
		return this.checkoutDt;
	}

	public void setCheckoutDt(Date checkoutDt) {
		this.checkoutDt = checkoutDt;
	}

	/**
	 * @return the bookingUser
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BOOKING_USER_ID", nullable = false)
	public TbookingUser getBookingUser() {
		return bookingUser;
	}

	/**
	 * @param bookingUser
	 *            the bookingUser to set
	 */
	public void setBookingUser(TbookingUser bookingUser) {
		this.bookingUser = bookingUser;
	}

	/**
	 * @return the noOfRoomsBooked
	 */
	@Column(name = "NO_OF_ROOMS_BOOKED", nullable = false, length = 20)
	public int getNoOfRoomsBooked() {
		return noOfRoomsBooked;
	}

	/**
	 * @param noOfRoomsBooked the noOfRoomsBooked to set
	 */
	public void setNoOfRoomsBooked(int noOfRoomsBooked) {
		this.noOfRoomsBooked = noOfRoomsBooked;
	}

	/**
	 * @return the hotel
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "HOTEL_ID", nullable = false)
	public Thotel getHotel() {
		return hotel;
	}

	/**
	 * @param hotel the hotel to set
	 */
	public void setHotel(Thotel hotel) {
		this.hotel = hotel;
	}

}
