CREATE DATABASE hotelmgmt;

use hotelmgmt;


--Table to hold all city information
CREATE TABLE TCITY
(CITY_ID INTEGER NOT NULL,
CITY_NM VARCHAR(50),
PRIMARY KEY (CITY_ID));


INSERT INTO TCITY VALUES(1,'Bengaluru');
INSERT INTO TCITY VALUES(2,'New Delhi');
INSERT INTO TCITY VALUES(3,'Kolkata');
INSERT INTO TCITY VALUES(4,'Mumbai');
INSERT INTO TCITY VALUES(5,'Hyderabad');
INSERT INTO TCITY VALUES(6,'Chennai');



CREATE TABLE THOTEL
(
HOTEL_ID INTEGER NOT NULL,
HOTEL_NM VARCHAR(50),
CITY_ID INTEGER NOT NULL,
LANDMARK VARCHAR(50),
NO_OF_ROOMS INTEGER NOT NULL,
RATING INTEGER NOT NULL,
TARIFF DOUBLE NOT NULL,
PRIMARY KEY(HOTEL_ID),
FOREIGN KEY(CITY_ID) REFERENCES TCITY(CITY_ID)
);

INSERT INTO THOTEL VALUES(1,'Vivanta by Taj',1,'Yashwantpur',25,5,10000);
INSERT INTO THOTEL VALUES(2,'The Leela Palace',1,'Old Airport Road',20,4,11000);
INSERT INTO THOTEL VALUES(3,'Sheraton Grand',1,'Rajaji Nagar',15,4,12000);
INSERT INTO THOTEL VALUES(4,'Vivanta By Taj',1,'MG Road',25,5,10000);
INSERT INTO THOTEL VALUES(5,'The Oberoi',1,'MG Road',15,4,10000);
INSERT INTO THOTEL VALUES(6,'Leela Palace',2,'Diplomatic Enclave',15,5,10000);
INSERT INTO THOTEL VALUES(7,'The Imperial',2,'Connaught Place',15,4,10000);
INSERT INTO THOTEL VALUES(8,'Vivanta by Taj Ambassador',2,'Subramaniam Bharti Marg',15,4,12000);
INSERT INTO THOTEL VALUES(9,'The Sonnet',3,'Salt Lake',15,4,13000);
INSERT INTO THOTEL VALUES(10,'Hotel Monotel',3,'Salt Lake',15,3,10000);
INSERT INTO THOTEL VALUES(11,'The Taj Mahal Palace',4,'Colaba',15,5,11000);
INSERT INTO THOTEL VALUES(12,'JW Marriott',4,'Juhu Tara Road',15,5,10000);
INSERT INTO THOTEL VALUES(13,'The Park',5,'Somajiguda',15,3,10000);
INSERT INTO THOTEL VALUES(14,'Trident',5,'Madhapur',15,3,10000);
INSERT INTO THOTEL VALUES(15,'Hilton',6,'Guindy',15,4,10000);
INSERT INTO THOTEL VALUES(16,'Radisson Blu Hotel',6,'St. Thomas Mount',15,5,10000);


CREATE TABLE TBOOKING_USER
(
BOOKING_USER_ID INTEGER NOT NULL,
BOOKING_REF_NO VARCHAR(20) NOT NULL,
BOOKING_DT TIMESTAMP NOT NULL,
TOTAL_PRICE DOUBLE NOT NULL,
PRIMARY KEY(BOOKING_USER_ID)
);

CREATE TABLE TBOOKED_ROOM_DETAILS
(
BOOKED_RM_DTL_ID INTEGER NOT NULL,
HOTEL_ID INTEGER NOT NULL,
NO_OF_ROOMS_BOOKED INTEGER NOT NULL,
BOOKING_USER_ID INTEGER NOT NULL,
CHECKIN_DT DATE NOT NULL,
CHECKOUT_DT DATE NOT NULL,
PRIMARY KEY(BOOKED_RM_DTL_ID),
FOREIGN KEY(HOTEL_ID) REFERENCES THOTEL(HOTEL_ID),
FOREIGN KEY(BOOKING_USER_ID) REFERENCES TBOOKING_USER(BOOKING_USER_ID)
);


ALTER TABLE TBOOKING_USER MODIFY COLUMN BOOKING_USER_ID INTEGER auto_increment;
ALTER TABLE TBOOKED_ROOM_DETAILS MODIFY COLUMN BOOKED_RM_DTL_ID INTEGER auto_increment;